CREATE DATABASE IF NOT EXISTS py_login
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE py_login;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(180) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
